### ISSUE TITLE
Add backend for the login/signup authenication

### ISSUE THREAD

**Issue by Aniketh01** [Aniketh01/pizza-ordering#7]

**Comment by ankurshr01** [comment]
like to work on it..
using django will work?

**Comment by Aniketh01** [comment]
@ankurshr01 Please go ahead. Try to add authentication with JAVA or JSP?

**Comment by VershaCoder** [comment]
Hi, 
Please elaborate on the issue. 
what exactly needs to implement.
Thanks.
